#! /bin/bash
### BEGIN INIT INFO
# Provides:            isk-server
# Required-Start:      nginx memcached redis
# Required-Stop:       nginx memcached redis 
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Start isk-server
# Description:         Start up isk-server, a slideshow management system
### END INIT INFO

# Usage:
# start, stop or restart

case "$1" in
  start)
       echo "Starting ISK-server..."
       TERM_CHILD=1 BACKGROUND=yes PIDFILE=tmp/pids/resque.pid QUEUE=* rake resque:work
	   script/background_jobs.rb start > /dev/null
	   script/rrd_monitoring.rb start > /dev/null
       rails s thin -d -p 12765 > /dev/null
       ;;
  stop)
       echo "Stopping ISK-server..."
       kill $(cat tmp/pids/resque.pid) &>/dev/null
       kill $(cat tmp/pids/background_jobs.pid) &>/dev/null
       kill $(cat tmp/pids/server.pid) &>/dev/null
	   kill $(cat tmp/pids/rrd_monitoring.pid) &>/dev/null
	   bin/spring stop
       ;;

  restart|force-reload)
       #
       #       If the "reload" option is implemented, move the "force-reload"
       #       option to the "reload" entry above. If not, "force-reload" is
       #       just the same as "restart".
       #
       echo "Restarting ISK-server..."
       kill $(cat tmp/pids/resque.pid) &>/dev/null
       TERM_CHILD=1 BACKGROUND=yes PIDFILE=tmp/pids/resque.pid QUEUE=* rake resque:work
	   script/background_jobs.rb restart > /dev/null
       kill $(cat tmp/pids/server.pid) &>/dev/null
       rails s thin -d -p 12765 > /dev/null
	   script/rrd_monitoring.rb restart
       ;;
  pull)
       echo "Updating sources..."
       git checkout db/schema.rb
       git pull
       bundle install
       rake db:migrate
       rake assets:precompile
       ./isk-server restart
       ;;
  *)
	echo "Usage: foo {start|stop|restart|pull}" >&2
	exit 1
	;;
esac

exit 0
